# 6-05. 예외 처리는 JUnit에게 맡기기

### AS-IS

- 첫 번째 테스트는 원인 사슬이 깨진다. 메시지만 제공할 뿐 전체 예외를 스택 추적으로 제공하지 않는다.
- 두 번째 테스트는 실제로 예외가 일어나길 기대하는데 코드로는 그 이유를 알 수 없다.

```java
class LogbookTest {
    
    @Test
    void readLogbook() {
        Logbook logbook = new Logbook();

        try {
            List<String> entries = logbook.readAllEntires();
            Assertions.assertEquals(13, entries.size());
        } catch (IOException e) {
            Assertions.fail(e.getMessage());
        }
    }

    @Test
    void readLogbookFail() {
        Logbook logbook = new Logbook();

        try {
            logbook.readAllEntires();
            Assertions.fail("read should fail");
        } catch (IOException ignored) {}
    }
}
```

### TO-BE

- `JUnit`이 제공하는 예외 처리 내장 메커니즘을 활용해라.
- 모든 `JUnit` 테스트는 '어떤 예외도 발생하지 않는다'는 암묵적인 어서션을 포함하고 있다.
- 예외가 발생하면 `JUnit`은 실패에 대한 전체 스택 추적을 표시한다.

```java
class LogbookTest {
    
    @Test
    void readLogbook() throws IOException {
        Logbook logbook = new Logbook();

        List<String> entries = logbook.readAllEntires();

        Assertions.assertEquals(13, entries.size());
    }

    @Test
    void readLogbookFail() {
        Logbook logbook = new Logbook();

        Executable when = () -> logbook.readAllEntires();

        Assertions.assertThrows(IOException.class, when);
    }
}
```
